- docs/introduction.md
> Copy edit in introduction

- docs/plugins.md
Added https://github.com/natzcam/conf-cli
> Add community plugins section

- docs/flags.md
Also document what the functions for defaults must return.
> Document that boolean flags can have defaults

- docs/supertable.md
- docs/table.md
- website/i18n/en.json
- website/sidebars.json
- website/yarn.lock
> add supertable

- docs/releasing.md
In relation to https://github.com/oclif/plugin-update/issues/53 and the Spectrum discussion I had with @jdxcode
> docs: explain writing a brew formula

- docs/prompting.md
better describe what hide does
> fix prompt's hide description

- website/blog/2018-03-20-introducing-oclif.md
This will stop facebook from dropping a cookie on this post
> remove facebookid

- website/blog/2020-05-05-introducing-custom-help-classes.md
> fix typo in introducing-custom-help-classes.md

- docs/commands.md
- docs/error_handling.md
- website/blog/2020-07-01-pretty-printable-errors.md
- website/i18n/en.json
- website/sidebars.json
* Add blog post and docs around pretty printable errors
* Add docs around error handling
> feat: add error docs

- docs/features.md
Since it likely isn't coming soon we can remove it from the website
> Remove man pages from coming soon

- docs/table.md
This pull request removes terms that are not inclusive.
> fix: use inclusive terms

- docs/hooks.md
Updating just the Hooks doc to reflect the new type of hook recently added .
> Added `postrun` to the list of Lifecycle Events

- docs/introduction.md
Updates the quick start example
Fixes https://github.com/oclif/oclif/issues/785
> fix: update Quickstart example

- docs/releasing.md
> fix: update releasing.md

- docs/table.md
@W-10678887@ as reported by oclif/core issue 369
> fix: correct example code

- website/sidebars.json
Fixes https://github.com/oclif/oclif/issues/998
> feat: add page on single command clis

- docs/aliases.md
- docs/args.md
- docs/base_class.md
- docs/esm.md
- docs/global_flags.md
- docs/prompting.md
- docs/spinner.md
- docs/table.md
Makes changes for v2 changes (https://github.com/oclif/core/pull/539)
> feat: v2 docs

- docs/esm.md
Fixes https://github.com/oclif/oclif/issues/1088
> fix: update ESM docs

- docs/error_handling.md
fixes https://github.com/oclif/core/issues/636
> fix: error handling

- docs/esm.md
Depends on https://github.com/oclif/core/pull/759
> feat: new esm docs

- docs/ES2022.md
- website/sidebars.json
Document changes required to successfully target ES2022
Fixes https://github.com/oclif/oclif/issues/1100
Fixes https://github.com/oclif/core/issues/745
@W-13897928@
> feat: doc fixes for ES2022 target

- docs/base_class.md
Fixes https://github.com/oclif/oclif/issues/1205
> fix: pass in enableJsonFlag

- docs/aliases.md
- docs/error_handling.md
- docs/introduction.md
- docs/nsis-installer_customization.md
- website/src/pages/index.js
Update references to `bin/run` with `bin/run.js` and `bin/dev` with `bin/dev.js`
Fixes [#1211](https://github.com/oclif/oclif/issues/1211)
> fix: update bin script references

- docs/args.md
- docs/config.md
- docs/examples.md
- docs/flags.md
- docs/generator_commands.md
- docs/how_we_work.md
- docs/plugins.md
- docs/related_repos.md
- docs/templates.md
- website/docusaurus.config.js
- website/sidebars.json
- Update documentation related to configuration, flag properties, etc...
- Update "overview" type documentation
@W-15285399@
@W-15285411@
> feat: update docs

- website/blog/2020-08-26-summer-update.md
- website/blog/2024-03-29-spring-update.md
Add spring 2024 blog with highlights from the past few years
@W-15362605@
> feat: add spring 24 blog

- .github/workflows/onPushToDocs.yml
Trigger reindex in Algolia after publish
> ci: trigger reindex on publish

- docs/configuring_your_cli.md
- docs/jit_plugins.md
- docs/logging.md
- docs/themes.md
- docs/user_experience.md
- website/docusaurus.config.ts
- website/sidebars.ts
Update docs for oclif/core v4
@W-15608512@
> feat: update docs for oclif/core v4

- docs/args.md
- website/package.json
- website/yarn.lock
> fix: document that args read from stdin

- docs/introduction.md
> fix: broken link

- docs/config.md
> chore: update config.md

- docs/testing.md
Added documentation to explain the required config needed when using vitest.
> Update testing.md for vitest.
