oclif/oclif.github.io

docs/releasing.md, docs/running_programmatically.md, docs/spinner.md
A few things I noticed while working through the docs:
- Had to search around a bit before I understood that "set `oclif.update.s3.host`" was setting in package.json. Now it's reiterated every time, and does not assume reading from start to finish
- In the shared code example, the shared code has to be exported
- The spinner documentation was missing necessary information on how to get `cli.action` to work. Found the info in the Prompting docs, and made the spinner docs match
=> Docs clarifications

docs/base_class.md
Improve the docs for custom command base class.
Hope this helps other folks to not go through the same misunderstanding mentioned at https://github.com/oclif/oclif/issues/374
=> Add return calls to base cmd error handling example

docs/help_classes.md
The option for `yarn add` should come after the package name.
=> Fix yarn command

docs/aliases.md, docs/args.md, docs/base_class.md, docs/commands.md, docs/flags.md, docs/prompting.md, docs/related_repos.md, docs/running_programmatically.md, docs/spinner.md, docs/table.md
=> fix: correct doc issues

docs/faqs.md, docs/introduction.md, website/blog/2021-03-01-introducing-oclif-core.md, website/blog/2022-01-12-announcing-oclif-v2.md
Just a minor clarification regarding support of Node's LTS versions. _Active LTS_ only refers to a **single** version, however support should (at least) **also include** the _Maintenance LTS_ version. Therefore, it is better to just generally refer to "LTS versions".
Also fixes a couple of minor typos that made their way into the repo since #70 was merged.
=> Clarify Node.js LTS support

docs/json.md
Otherwise, it leads to an error
```
Class static side 'typeof HelloCommand' incorrectly extends base class static side 'typeof Command'.
Property 'enableJsonFlag' is private in type 'typeof HelloCommand' but not in type 'typeof Command'.
```
=> Update Readme example

docs/args.md
We have to await for the `this.parse(MyCLI)`.
=> Awaiting this.parse(MyCLI) for the response

docs/args.md, docs/base_class.md, docs/prompting.md, docs/running_programmatically.md, docs/table.md
Adds `await` to all the `this.parse()` statements in the docs to match the oclif v2.
=> fix(docs): await this.parse in all docs

docs/hooks.md
Noticed some hooks examples in docs using `export default const`, which I'm not sure is a standard ES Modules syntax - refactoring to separate exports.
=> docs: fix hooks example export default const

website/blog/2020-05-05-introducing-custom-help-classes.md
Existing link lands at https://oclif.io/blog/2020/docs/help_classes which results in 404. New link lands at correct page https://oclif.io/docs/help_classes
=> Updated help_classes link

docs/base_class.md
Fixes the example for a base command class to be compilable and type safe
Closes #142 
Closes https://github.com/oclif/oclif/issues/577
=> fix: base class example

docs/plugins.md
Adds a link to [dynamic-commands](https://www.npmjs.com/package/oclif-dynamic-commands) under the "Community Plugins" section.
=> Update plugins.md with link to `dynamic-commands` plugin

docs/prompting.md
Updates prompting/inquirer section to add an example using inquirer v9 (ESM) in a CommonJS CLI/plugin.
Closes: https://github.com/oclif/core/issues/476
=> fix prompting/inquirer section

docs/releasing.md
Added description on how to set ACL for upload to S3 command as well as an example from package.json
=> Documentation update [releasing.md] - adding description of ACL setting for upload command

docs/releasing.md
Added example of configuration in package.json and more details on how to sign a macos package by creating appropriate certificate, where to locate it and how to configure it.
=> Documentation update to [releasing.md] with MacOs signing information

docs/themes.md, website/sidebars.json
Document `themes` functionality
Depends on https://github.com/oclif/core/pull/862/
@W-14455216@
=> feat: document themes

docs/commands.md
Remove references to `@oclif/errors`
Closes #194
=> fix: update error information in commands.md

docs/esm.md, docs/releasing.md
=> feat: update release docs

.github/workflows/onPushToDocs.yml
This was part of the "make our workflows more 3rd party friendly". We were hard coding the username and email for our SVC github user. Now it looks up that git info from the Token you are using.
=> Update gitConfig lookup

docs/introduction.md
=> feat: improve introduction

docs/user_experience.md
This is a very tiny fix, but there's an important missing word in the first sentence of this docs page.
=> Fix typo in UX guide

docs/faqs.md, docs/features.md, docs/generator_commands.md, docs/introduction.md, docs/templates.md
Mostly just a copy edit, although I periodically added a bit of context when I think it needed it.
=> edit of the Getting Started topics

docs/performance.md
The docs say to set the DEBUG variable to `oclif-perf` to view perf data, but it seems to be `oclif:perf` instead.
=> Correct DEBUG variable setting for perf metrics

docs/hooks.md
Update docs for https://github.com/oclif/core/pull/1276
@W-17482601@
=> chore: update hooks
